"""Structured LLM outputs.

Every prompt asks the model for a single JSON object that validates against
one of these schemas.  Parsing raw prose is never allowed: the LLM service
repairs and retries until the payload validates (or gives up and raises).
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class QuestionDraft(BaseModel):
    """A single base question generated by the planner."""

    question: str = Field(..., min_length=10)
    topic: str = Field(..., min_length=2)
    intent: str = Field(default="", description="What the interviewer probes")
    question_type: Literal[
        "definition", "conceptual", "scenario", "architecture",
        "debugging", "tradeoffs", "design", "production",
        "deployment", "reasoning",
    ]

    @field_validator("question")
    @classmethod
    def question_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("question must not be blank")
        return v.strip()


class EvaluationDraft(BaseModel):
    """Rating of a single candidate answer plus the next-move decision."""

    score: int = Field(..., ge=0, le=10)
    verdict: Literal["excellent", "good", "weak", "wrong", "unclear"]
    follow_up: Literal["deeper", "simplify", "recovery", "next_topic", "probe"]
    mastered_topic: bool = Field(
        default=False, description="Whether the topic is now considered covered"
    )
    notes: str = Field(default="", description="Short private rationale")


class FollowUpDraft(BaseModel):
    """A follow-up question adapted to the candidate's last answer."""

    question: str = Field(..., min_length=10)
    intent: str = Field(default="")
    difficulty: Literal["easy", "medium", "advanced"]


class FeedbackDraft(BaseModel):
    """Final structured feedback.

    ``score`` / ``confidence`` / ``topics_covered`` are computed for the
    backend only and never exposed through the API, which only serialises
    ``summary`` / ``strengths`` / ``gaps`` / ``next``.
    """

    summary: str = Field(..., min_length=10)
    strengths: list[str] = Field(..., min_length=1)
    gaps: list[str] = Field(..., min_length=1)
    next: list[str] = Field(..., min_length=1)
    score: int = Field(..., ge=0, le=100)
    confidence: float = Field(..., ge=0.0, le=1.0)
    topics_covered: list[str] = Field(default_factory=list)


class FeedbackResult(BaseModel):
    """The persisted feedback object (internal superset of the API shape)."""

    summary: str
    strengths: list[str]
    gaps: list[str]
    next: list[str]
    score: int
    confidence: float
    topics_covered: list[str]

    def to_api_payload(self) -> dict:
        """Expose ONLY the fields required by the specification."""
        return {
            "summary": self.summary,
            "strengths": list(self.strengths),
            "gaps": list(self.gaps),
            "next": list(self.next),
        }
